name: Next-Colors CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test-and-update-docs:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run packup
            - run: npm test
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            # Generate docs (only for Node.js 20.x)
            - name: Generate documentation
              if: matrix.node-version == '20.x' && github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: npm run docs

            # Commit and push if there are any changes (only for Node.js 20.x and push to main)
            - name: Commit and push changes
              if: matrix.node-version == '20.x' && github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add docs
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update documentation" && git push)
