name: color-core CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-and-update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Generate docs
      - name: Generate documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm run docs

      # Commit and push if there are any changes
      - name: Commit and push changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update documentation" && git push)
